name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Build Docker Image
        run: docker build -t myfastapiapp .

      - name: Run Tests in Docker Container
        run: docker run myfastapiapp pytest